### ISSUE TITLE
request: Dispatch Sound Progress Event when loading sounds

### ISSUE THREAD

**Issue by grantbridges** [DigitalStrawberry/ANE-Sounds#14]
I want to be able to load songs on demand at different points within my app, and it'd be nice to catch progress events during song loading to present a load percentage to the user.  Seems like it'd be a pretty simple addition to the SoundEvent class, along with an extra event dispatch?

Much appreciate this ANE, it's been tremendously helpful!

**Comment by marpies** [comment]
We don't really have any progress information from the system when loading the sounds on Android, so it's not possible to implement this feature on all platforms.

If you are loading multiple files at once then you could show at least some sort of progress by updating the progress bar as you receive the `LOAD` event, or simply use an indeterminate progress indicator instead.

Also consider that the sound files used with this ANE are generally very small and attempting to show an actual progress bar may not result in the visual feedback you want, since the progress is very likely just going to go from 0 to 100 in the span of a few frames.
