### ISSUE TITLE
Cutting off sounds with the same id and no polyphony on Android

### ISSUE THREAD

**Issue by SlavomirDurej** [DigitalStrawberry/ANE-Sounds#6]
Some of the testers of my virtual keyboard app has reported this issue and I can confirm it is indeed happening. Verified this on iPad Air 2, and some Android devices as well. 

When playing the sound with the certain ID, and then playing the sound with the same ID the first sound get cut off! Instead of letting the first sound finish playing... This is not a problem if the second sound has a different ID.

as well , on iOS you allow for polyphony (so several sounds can play at once but not on Android).

Would you be able to take a look please? Would hugely appreciate it!

**Comment by ecornbower** [comment]
Thanks for the report, we'll look into this.

**Comment by BigMageGameStudios** [comment]
we fall on the same issue. The solution could be 
SoundPool.Builder().setMaxStreams( gratherThanOneValue); // :)
Maybe this should be configurable from AS3 code

**Comment by ecornbower** [comment]
@marpies Could you take a look into this and see how difficult it would be to fix?

**Comment by marpies** [comment]
Apologies for the delay in resolving the issue.

We've added new APIs in the [v1.4 release](https://github.com/DigitalStrawberry/ANE-Sounds/releases/tag/v1.4). You can now specify the maximum streams allowed on Android:

```as3
ANESounds.setMaxStreams(30);
```

Now that each sound can have multiple streams, you will need to keep track of the stream id (`int`) returned by the `playSound` method, if you wish to further interact with the stream. Note the `stopSound` method has been renamed to `stopStream` (you must provide the stream id instead of sound id). You also need the stream id when using the `setVolume` method.

See updated readme page for further info, and let us know if you encounter any issues.

**Comment by SlavomirDurej** [comment]
Just wanted to say BIG thanks guys for implementing this, just dropped the new ANE in and it worked like a charm! You're my heroes!

**Comment by ecornbower** [comment]
@SlavomirDurej You're welcome!
